language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build:prod
before_deploy: "echo 'start'"
deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  tag: next
  on:
    branch: master
after_deploy: "echo 'finish?'"
